steps:
  - id: 'restore-cache'
    name: 'us-docker.pkg.dev/vargolabs/gcs-cacher/gcs-cacher:0.1'
    args:
      - '-bucket=$PROJECT_ID-$REPO_NAME-cloudbuild-cache'
      - '-restore=gradle-{{ hashGlob "build.gradle.kts" }}'
      - '-dir=/.gradle'
      - '-allow-failure'
    volumes:
      - name: 'gradle'
        path: '/.gradle'

  - id: 'build-container'
    name: 'gcr.io/cloud-builders/javac:8'
    entrypoint: './gradlew'
    args: ['--console=plain', '--no-daemon', 'jib', '-Djib.to.image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
    volumes:
      - name: 'gradle'
        path: '/.gradle'

  - id: 'save-cache'
    name: 'us-docker.pkg.dev/vargolabs/gcs-cacher/gcs-cacher:0.1'
    args:
      - '-bucket=$PROJECT_ID-$REPO_NAME-cloudbuild-cache'
      - '-cache=gradle-{{ hashGlob "build.gradle.kts" }}'
      - '-dir=/.gradle'
    volumes:
      - name: 'gradle'
        path: '/.gradle'

  - id: 'deploy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', '--quiet', '--image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '--platform=managed', '--project=$PROJECT_ID', '--region=us-central1', '--allow-unauthenticated', '--memory=512Mi', '--cpu=2', '$REPO_NAME']
