steps:
- name: 'gcr.io/cloud-builders/javac:8'
  entrypoint: './gradlew'
  args: ['jibDockerBuild']
- name: 'gcr.io/cloud-builders/javac:8'
  entrypoint: 'printenv'
  args: ['PROJECT_ID']
images: ['gcr.io/$PROJECT_ID/where-am-i']
